/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioB38c6a29RouteImport } from './routes/studio-b38c6a29'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioB38c6a29Route = StudioB38c6a29RouteImport.update({
  id: '/studio-b38c6a29',
  path: '/studio-b38c6a29',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio-b38c6a29': typeof StudioB38c6a29Route
  '/articles/$slug': typeof ArticlesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio-b38c6a29': typeof StudioB38c6a29Route
  '/articles/$slug': typeof ArticlesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio-b38c6a29': typeof StudioB38c6a29Route
  '/articles/$slug': typeof ArticlesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio-b38c6a29'
    | '/articles/$slug'
    | '/collections/$slug'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio-b38c6a29'
    | '/articles/$slug'
    | '/collections/$slug'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/studio-b38c6a29'
    | '/articles/$slug'
    | '/collections/$slug'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioB38c6a29Route: typeof StudioB38c6a29Route
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-b38c6a29': {
      id: '/studio-b38c6a29'
      path: '/studio-b38c6a29'
      fullPath: '/studio-b38c6a29'
      preLoaderRoute: typeof StudioB38c6a29RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioB38c6a29Route: StudioB38c6a29Route,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
